name: python-fr
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - setuptools
  # Dev Tools
  - black
  # CLI
  - plumbum
  - tqdm
  - typer
  # Scientific Stack
  - numpy
  - autograd
  - scipy
  - matplotlib
  - pillow
  - ffmpeg
  - sympy
  # Jupyter Notebooks
  - jupyter
  - nbconvert
  - jupytext
  # Document Processing 
  - beautifulsoup4
  - pandoc=2.18

  - pip:
    # Pygame
    - pygame
    # Document Processing
    - pandoc==2.2

